version: 2
jobs:
  build:
    machine: true
    
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Get Docker
          command: curl https://get.docker.com | bash 
      - run:
          name: CI-Build
          command: docker run -v $(pwd):/pkg whynothugo/makepkg
