version: 2
jobs:
  build:
    docker:
      - image: base/devel
    steps:
      - checkout
      - run:
          name: Upgrade System
          command: pacman -Syu --noconfirm
      - run:
          name: Make Package
          command: pacman -S --needed --noconfirm sudo # Install sudo
          command: useradd builduser -m # Create the builduser
          command: passwd -d builduser
          command: printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers # Allow the builduser passwordless sudo
          command: makepkg
