version: 2
jobs:
  build:
    docker:
      - image: base/devel
    steps:
      - checkout
      - run:
          name: Prepare
          command: pacman -Syu --noconfirm
          command: pacman-key --init
          command: pacman-key --populate archlinux
      - run:
          name: Make Package
          command: useradd build -m
          command: passwd -d build
          command: su build -c makepkg
