version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker
      - run:
          name: Make Package
          command: docker run -v $(pwd):/pkg whynothugo/makepkg
          
