version: 2
jobs:
  build:
    docker:
      - image: aitorpazos/archlinux-docker-makepkg
    steps:
      - checkout
      - run:
          name: Prepare
          command: pacman -Syu --noconfirm
          command: pacman-key --populate archlinux
      - run:
          name: Make Package
          command: su makepkg -c makepkg
